create table if not exists public.capycatch_scores (
  id bigint generated by default as identity primary key,
  player_name text not null check (char_length(player_name) between 1 and 18),
  score integer not null check (score between 0 and 100000),
  combo integer not null check (combo between 1 and 4),
  mode text not null check (mode in ('classic', 'endless', 'chaos', 'daily')),
  created_at timestamptz not null default now()
);

create index if not exists capycatch_scores_mode_score_idx
  on public.capycatch_scores (mode, score desc, created_at asc);

alter table public.capycatch_scores enable row level security;

drop policy if exists "capycatch public read" on public.capycatch_scores;
create policy "capycatch public read"
  on public.capycatch_scores
  for select
  to anon
  using (true);

drop policy if exists "capycatch public insert" on public.capycatch_scores;
create policy "capycatch public insert"
  on public.capycatch_scores
  for insert
  to anon
  with check (
    score between 0 and 100000
    and combo between 1 and 4
    and mode in ('classic', 'endless', 'chaos', 'daily')
    and char_length(player_name) between 1 and 18
  );

grant select, insert on public.capycatch_scores to anon;
grant usage, select on sequence public.capycatch_scores_id_seq to anon;
